import React from "react";
import PropTypes from "prop-types";
import { Link } from "react-router-dom";
import SelectLocation from "../dropdown";
import Select from "react-select";

FormContent.propTypes = {};

function FormContent(props) {
  const options = [
    { lable: "Afghanistan", value: "AF" },
    { lable: "Åland Islands", value: "AX" },
    { lable: "Albania", value: "AL" },
    { lable: "Algeria", value: "DZ" },
    { lable: "American Samoa", value: "AS" },
    { lable: "AndorrA", value: "AD" },
    { lable: "Angola", value: "AO" },
    { lable: "Anguilla", value: "AI" },
    { lable: "Antarctica", value: "AQ" },
    { lable: "Antigua and Barbuda", value: "AG" },
    { lable: "Argentina", value: "AR" },
    { lable: "Armenia", value: "AM" },
    { lable: "Aruba", value: "AW" },
    { lable: "Australia", value: "AU" },
    { lable: "Austria", value: "AT" },
    { lable: "Azerbaijan", value: "AZ" },
    { lable: "Bahamas", value: "BS" },
    { lable: "Bahrain", value: "BH" },
    { lable: "Bangladesh", value: "BD" },
    { lable: "Barbados", value: "BB" },
    { lable: "Belarus", value: "BY" },
    { lable: "Belgium", value: "BE" },
    { lable: "Belize", value: "BZ" },
    { lable: "Benin", value: "BJ" },
    { lable: "Bermuda", value: "BM" },
    { lable: "Bhutan", value: "BT" },
    { lable: "Bolivia", value: "BO" },
    { lable: "Bosnia and Herzegovina", value: "BA" },
    { lable: "Botswana", value: "BW" },
    { lable: "Bouvet Island", value: "BV" },
    { lable: "Brazil", value: "BR" },
    { lable: "British Indian Ocean Territory", value: "IO" },
    { lable: "Brunei Darussalam", value: "BN" },
    { lable: "Bulgaria", value: "BG" },
    { lable: "Burkina Faso", value: "BF" },
    { lable: "Burundi", value: "BI" },
    { lable: "Cambodia", value: "KH" },
    { lable: "Cameroon", value: "CM" },
    { lable: "Canada", value: "CA" },
    { lable: "Cape Verde", value: "CV" },
    { lable: "Cayman Islands", value: "KY" },
    { lable: "Central African Republic", value: "CF" },
    { lable: "Chad", value: "TD" },
    { lable: "Chile", value: "CL" },
    { lable: "China", value: "CN" },
    { lable: "Christmas Island", value: "CX" },
    { lable: "Cocos (Keeling) Islands", value: "CC" },
    { lable: "Colombia", value: "CO" },
    { lable: "Comoros", value: "KM" },
    { lable: "Congo", value: "CG" },
    { lable: "Congo, The Democratic Republic of the", value: "CD" },
    { lable: "Cook Islands", value: "CK" },
    { lable: "Costa Rica", value: "CR" },
    { lable: "Cote D'Ivoire", value: "CI" },
    { lable: "Croatia", value: "HR" },
    { lable: "Cuba", value: "CU" },
    { lable: "Cyprus", value: "CY" },
    { lable: "Czech Republic", value: "CZ" },
    { lable: "Denmark", value: "DK" },
    { lable: "Djibouti", value: "DJ" },
    { lable: "Dominica", value: "DM" },
    { lable: "Dominican Republic", value: "DO" },
    { lable: "Ecuador", value: "EC" },
    { lable: "Egypt", value: "EG" },
    { lable: "El Salvador", value: "SV" },
    { lable: "Equatorial Guinea", value: "GQ" },
    { lable: "Eritrea", value: "ER" },
    { lable: "Estonia", value: "EE" },
    { lable: "Ethiopia", value: "ET" },
    { lable: "Falkland Islands (Malvinas)", value: "FK" },
    { lable: "Faroe Islands", value: "FO" },
    { lable: "Fiji", value: "FJ" },
    { lable: "Finland", value: "FI" },
    { lable: "France", value: "FR" },
    { lable: "French Guiana", value: "GF" },
    { lable: "French Polynesia", value: "PF" },
    { lable: "French Southern Territories", value: "TF" },
    { lable: "Gabon", value: "GA" },
    { lable: "Gambia", value: "GM" },
    { lable: "Georgia", value: "GE" },
    { lable: "Germany", value: "DE" },
    { lable: "Ghana", value: "GH" },
    { lable: "Gibraltar", value: "GI" },
    { lable: "Greece", value: "GR" },
    { lable: "Greenland", value: "GL" },
    { lable: "Grenada", value: "GD" },
    { lable: "Guadeloupe", value: "GP" },
    { lable: "Guam", value: "GU" },
    { lable: "Guatemala", value: "GT" },
    { lable: "Guernsey", value: "GG" },
    { lable: "Guinea", value: "GN" },
    { lable: "Guinea-Bissau", value: "GW" },
    { lable: "Guyana", value: "GY" },
    { lable: "Haiti", value: "HT" },
    { lable: "Heard Island and Mcdonald Islands", value: "HM" },
    { lable: "Holy See (Vatican City State)", value: "VA" },
    { lable: "Honduras", value: "HN" },
    { lable: "Hong Kong", value: "HK" },
    { lable: "Hungary", value: "HU" },
    { lable: "Iceland", value: "IS" },
    { lable: "India", value: "IN" },
    { lable: "Indonesia", value: "ID" },
    { lable: "Iran, Islamic Republic Of", value: "IR" },
    { lable: "Iraq", value: "IQ" },
    { lable: "Ireland", value: "IE" },
    { lable: "Isle of Man", value: "IM" },
    { lable: "Israel", value: "IL" },
    { lable: "Italy", value: "IT" },
    { lable: "Jamaica", value: "JM" },
    { lable: "Japan", value: "JP" },
    { lable: "Jersey", value: "JE" },
    { lable: "Jordan", value: "JO" },
    { lable: "Kazakhstan", value: "KZ" },
    { lable: "Kenya", value: "KE" },
    { lable: "Kiribati", value: "KI" },
    { lable: "Korea, Democratic People'S Republic of", value: "KP" },
    { lable: "Korea, Republic of", value: "KR" },
    { lable: "Kuwait", value: "KW" },
    { lable: "Kyrgyzstan", value: "KG" },
    { lable: "Lao People'S Democratic Republic", value: "LA" },
    { lable: "Latvia", value: "LV" },
    { lable: "Lebanon", value: "LB" },
    { lable: "Lesotho", value: "LS" },
    { lable: "Liberia", value: "LR" },
    { lable: "Libyan Arab Jamahiriya", value: "LY" },
    { lable: "Liechtenstein", value: "LI" },
    { lable: "Lithuania", value: "LT" },
    { lable: "Luxembourg", value: "LU" },
    { lable: "Macao", value: "MO" },
    { lable: "Macedonia, The Former Yugoslav Republic of", value: "MK" },
    { lable: "Madagascar", value: "MG" },
    { lable: "Malawi", value: "MW" },
    { lable: "Malaysia", value: "MY" },
    { lable: "Maldives", value: "MV" },
    { lable: "Mali", value: "ML" },
    { lable: "Malta", value: "MT" },
    { lable: "Marshall Islands", value: "MH" },
    { lable: "Martinique", value: "MQ" },
    { lable: "Mauritania", value: "MR" },
    { lable: "Mauritius", value: "MU" },
    { lable: "Mayotte", value: "YT" },
    { lable: "Mexico", value: "MX" },
    { lable: "Micronesia, Federated States of", value: "FM" },
    { lable: "Moldova, Republic of", value: "MD" },
    { lable: "Monaco", value: "MC" },
    { lable: "Mongolia", value: "MN" },
    { lable: "Montserrat", value: "MS" },
    { lable: "Morocco", value: "MA" },
    { lable: "Mozambique", value: "MZ" },
    { lable: "Myanmar", value: "MM" },
    { lable: "Namibia", value: "NA" },
    { lable: "Nauru", value: "NR" },
    { lable: "Nepal", value: "NP" },
    { lable: "Netherlands", value: "NL" },
    { lable: "Netherlands Antilles", value: "AN" },
    { lable: "New Caledonia", value: "NC" },
    { lable: "New Zealand", value: "NZ" },
    { lable: "Nicaragua", value: "NI" },
    { lable: "Niger", value: "NE" },
    { lable: "Nigeria", value: "NG" },
    { lable: "Niue", value: "NU" },
    { lable: "Norfolk Island", value: "NF" },
    { lable: "Northern Mariana Islands", value: "MP" },
    { lable: "Norway", value: "NO" },
    { lable: "Oman", value: "OM" },
    { lable: "Pakistan", value: "PK" },
    { lable: "Palau", value: "PW" },
    { lable: "Palestinian Territory, Occupied", value: "PS" },
    { lable: "Panama", value: "PA" },
    { lable: "Papua New Guinea", value: "PG" },
    { lable: "Paraguay", value: "PY" },
    { lable: "Peru", value: "PE" },
    { lable: "Philippines", value: "PH" },
    { lable: "Pitcairn", value: "PN" },
    { lable: "Poland", value: "PL" },
    { lable: "Portugal", value: "PT" },
    { lable: "Puerto Rico", value: "PR" },
    { lable: "Qatar", value: "QA" },
    { lable: "Reunion", value: "RE" },
    { lable: "Romania", value: "RO" },
    { lable: "Russian Federation", value: "RU" },
    { lable: "RWANDA", value: "RW" },
    { lable: "Saint Helena", value: "SH" },
    { lable: "Saint Kitts and Nevis", value: "KN" },
    { lable: "Saint Lucia", value: "LC" },
    { lable: "Saint Pierre and Miquelon", value: "PM" },
    { lable: "Saint Vincent and the Grenadines", value: "VC" },
    { lable: "Samoa", value: "WS" },
    { lable: "San Marino", value: "SM" },
    { lable: "Sao Tome and Principe", value: "ST" },
    { lable: "Saudi Arabia", value: "SA" },
    { lable: "Senegal", value: "SN" },
    { lable: "Serbia and Montenegro", value: "CS" },
    { lable: "Seychelles", value: "SC" },
    { lable: "Sierra Leone", value: "SL" },
    { lable: "Singapore", value: "SG" },
    { lable: "Slovakia", value: "SK" },
    { lable: "Slovenia", value: "SI" },
    { lable: "Solomon Islands", value: "SB" },
    { lable: "Somalia", value: "SO" },
    { lable: "South Africa", value: "ZA" },
    { lable: "South Georgia and the South Sandwich Islands", value: "GS" },
    { lable: "Spain", value: "ES" },
    { lable: "Sri Lanka", value: "LK" },
    { lable: "Sudan", value: "SD" },
    { lable: "Suriname", value: "SR" },
    { lable: "Svalbard and Jan Mayen", value: "SJ" },
    { lable: "Swaziland", value: "SZ" },
    { lable: "Sweden", value: "SE" },
    { lable: "Switzerland", value: "CH" },
    { lable: "Syrian Arab Republic", value: "SY" },
    { lable: "Taiwan, Province of China", value: "TW" },
    { lable: "Tajikistan", value: "TJ" },
    { lable: "Tanzania, United Republic of", value: "TZ" },
    { lable: "Thailand", value: "TH" },
    { lable: "Timor-Leste", value: "TL" },
    { lable: "Togo", value: "TG" },
    { lable: "Tokelau", value: "TK" },
    { lable: "Tonga", value: "TO" },
    { lable: "Trinidad and Tobago", value: "TT" },
    { lable: "Tunisia", value: "TN" },
    { lable: "Turkey", value: "TR" },
    { lable: "Turkmenistan", value: "TM" },
    { lable: "Turks and Caicos Islands", value: "TC" },
    { lable: "Tuvalu", value: "TV" },
    { lable: "Uganda", value: "UG" },
    { lable: "Ukraine", value: "UA" },
    { lable: "United Arab Emirates", value: "AE" },
    { lable: "United Kingdom", value: "GB" },
    { lable: "United States", value: "US" },
    { lable: "United States Minor Outlying Islands", value: "UM" },
    { lable: "Uruguay", value: "UY" },
    { lable: "Uzbekistan", value: "UZ" },
    { lable: "Vanuatu", value: "VU" },
    { lable: "Venezuela", value: "VE" },
    { lable: "Viet Nam", value: "VN" },
    { lable: "Virgin Islands, British", value: "VG" },
    { lable: "Virgin Islands, U.S.", value: "VI" },
    { lable: "Wallis and Futuna", value: "WF" },
    { lable: "Western Sahara", value: "EH" },
    { lable: "Yemen", value: "YE" },
    { lable: "Zambia", value: "ZM" },
    { lable: "Zimbabwe", value: "ZW" },
  ];

  
  const countries = [
    {value: "Afghanistan",label: "AF",id: 1},
    {value: "Aland Islands",label: "AX",id: 2},
    {value: "Albania",label: "AL",id: 3},
    {value: "Algeria",label: "DZ",id: 4},
    {value: "American Samoa",label: "AS",id: 5},
    {value: "Andorra",label: "AD",id: 6},
    {value: "Angola",label: "AO",id: 7},
    {value: "Anguilla",label: "AI",id: 8},
    {value: "Antarctica",label: "AQ",id: 9},
    {value: "Antigua and Barbuda",label: "AG",id: 10},
    {value: "Argentina",label: "AR",id: 11},
    {value: "Armenia",label: "AM",id: 12},
    {value: "Aruba",label: "AW",id: 13},
    {value: "Australia",label: "AU",id: 14},
    {value: "Austria",label: "AT",id: 15},
    {value: "Azerbaijan",label: "AZ",id: 16},
    {value: "Bahamas",label: "BS",id: 17},
    {value: "Bahrain",label: "BH",id: 18},
    {value: "Bangladesh",label: "BD",id: 19},
    {value: "Barbados",label: "BB",id: 20},
    {value: "Belarus",label: "BY",id: 21},
    {value: "Belgium",label: "BE",id: 22},
    {value: "Belize",label: "BZ",id: 23},
    {value: "Benin",label: "BJ",id: 24},
    {value: "Bermuda",label: "BM",id: 25},
    {value: "Bhutan",label: "BT",id: 26},
    {value: "Bolivia",label: "BO",id: 27},
    {value: "Bonaire, Sint Eustatius and Saba",label: "BQ",id: 28},
    {value: "Bosnia and Herzegovina",label: "BA",id: 29},
    {value: "Botswana",label: "BW",id: 30},
    {value: "Bouvet Island",label: "BV",id: 31},
    {value: "Brazil",label: "BR",id: 32},
    {value: "British Indian Ocean Territory",label: "IO",id: 33},
    {value: "Brunei Darussalam",label: "BN",id: 34},
    {value: "Bulgaria",label: "BG",id: 35},
    {value: "Burkina Faso",label: "BF",id: 36},
    {value: "Burundi",label: "BI",id: 37},
    {value: "Cambodia",label: "KH",id: 38},
    {value: "Cameroon",label: "CM",id: 39},
    {value: "Canada",label: "CA",id: 40},
    {value: "Cape Verde",label: "CV",id: 41},
    {value: "Cayman Islands",label: "KY",id: 42},
    {value: "Central African Republic",label: "CF",id: 43},
    {value: "Chad",label: "TD",id: 44},
    {value: "Chile",label: "CL",id: 45},
    {value: "China",label: "CN",id: 46},
    {value: "Christmas Island",label: "CX",id: 47},
    {value: "Cocos (Keeling) Islands",label: "CC",id: 48},
    {value: "Colombia",label: "CO",id: 49},
    {value: "Comoros",label: "KM",id: 50},
    {value: "Congo",label: "CG",id: 51},
    {value: "Congo, Democratic Republic of the Congo",label: "CD",id: 52},
    {value: "Cook Islands",label: "CK",id: 53},
    {value: "Costa Rica",label: "CR",id: 54},
    {value: "Cote D'Ivoire",label: "CI",id: 55},
    {value: "Croatia",label: "HR",id: 56},
    {value: "Cuba",label: "CU",id: 57},
    {value: "Curacao",label: "CW",id: 58},
    {value: "Cyprus",label: "CY",id: 59},
    {value: "Czech Republic",label: "CZ",id: 60},
    {value: "Denmark",label: "DK",id: 61},
    {value: "Djibouti",label: "DJ",id: 62},
    {value: "Dominica",label: "DM",id: 63},
    {value: "Dominican Republic",label: "DO",id: 64},
    {value: "Ecuador",label: "EC",id: 65},
    {value: "Egypt",label: "EG",id: 66},
    {value: "El Salvador",label: "SV",id: 67},
    {value: "Equatorial Guinea",label: "GQ",id: 68},
    {value: "Eritrea",label: "ER",id: 69},
    {value: "Estonia",label: "EE",id: 70},
    {value: "Ethiopia",label: "ET",id: 71},
    {value: "Falkland Islands (Malvinas)",label: "FK",id: 72},
    {value: "Faroe Islands",label: "FO",id: 73},
    {value: "Fiji",label: "FJ",id: 74},
    {value: "Finland",label: "FI",id: 75},
    {value: "France",label: "FR",id: 76},
    {value: "French Guiana",label: "GF",id: 77},
    {value: "French Polynesia",label: "PF",id: 78},
    {value: "French Southern Territories",label: "TF",id: 79},
    {value: "Gabon",label: "GA",id: 80},
    {value: "Gambia",label: "GM",id: 81},
    {value: "Georgia",label: "GE",id: 82},
    {value: "Germany",label: "DE",id: 83},
    {value: "Ghana",label: "GH",id: 84},
    {value: "Gibraltar",label: "GI",id: 85},
    {value: "Greece",label: "GR",id: 86},
    {value: "Greenland",label: "GL",id: 87},
    {value: "Grenada",label: "GD",id: 88},
    {value: "Guadeloupe",label: "GP",id: 89},
    {value: "Guam",label: "GU",id: 90},
    {value: "Guatemala",label: "GT",id: 91},
    {value: "Guernsey",label: "GG",id: 92},
    {value: "Guinea",label: "GN",id: 93},
    {value: "Guinea-Bissau",label: "GW",id: 94},
    {value: "Guyana",label: "GY",id: 95},
    {value: "Haiti",label: "HT",id: 96},
    {value: "Heard Island and McDonald Islands",label: "HM",id: 97},
    {value: "Holy See (Vatican City State)",label: "VA",id: 98},
    {value: "Honduras",label: "HN",id: 99},
    {value: "Hong Kong",label: "HK",id: 100},
    {value: "Hungary",label: "HU",id: 101},
    {value: "Iceland",label: "IS",id: 102},
    {value: "India",label: "IN",id: 103},
    {value: "Indonesia",label: "ID",id: 104},
    {value: "Iran, Islamic Republic of",label: "IR",id: 105},
    {value: "Iraq",label: "IQ",id: 106},
    {value: "Ireland",label: "IE",id: 107},
    {value: "Isle of Man",label: "IM",id: 108},
    {value: "Israel",label: "IL",id: 109},
    {value: "Italy",label: "IT",id: 110},
    {value: "Jamaica",label: "JM",id: 111},
    {value: "Japan",label: "JP",id: 112},
    {value: "Jersey",label: "JE",id: 113},
    {value: "Jordan",label: "JO",id: 114},
    {value: "Kazakhstan",label: "KZ",id: 115},
    {value: "Kenya",label: "KE",id: 116},
    {value: "Kiribati",label: "KI",id: 117},
    {value: "Korea, Democratic People's Republic of",label: "KP",id: 118},
    {value: "Korea, Republic of",label: "KR",id: 119},
    {value: "Kosovo",label: "XK",id: 120},
    {value: "Kuwait",label: "KW",id: 121},
    {value: "Kyrgyzstan",label: "KG",id: 122},
    {value: "Lao People's Democratic Republic",label: "LA",id: 123},
    {value: "Latvia",label: "LV",id: 124},
    {value: "Lebanon",label: "LB",id: 125},
    {value: "Lesotho",label: "LS",id: 126},
    {value: "Liberia",label: "LR",id: 127},
    {value: "Libyan Arab Jamahiriya",label: "LY",id: 128},
    {value: "Liechtenstein",label: "LI",id: 129},
    {value: "Lithuania",label: "LT",id: 130},
    {value: "Luxembourg",label: "LU",id: 131},
    {value: "Macao",label: "MO",id: 132},
    {value: "Macedonia, the Former Yugoslav Republic of",label: "MK",id: 133},
    {value: "Madagascar",label: "MG",id: 134},
    {value: "Malawi",label: "MW",id: 135},
    {value: "Malaysia",label: "MY",id: 136},
    {value: "Maldives",label: "MV",id: 137},
    {value: "Mali",label: "ML",id: 138},
    {value: "Malta",label: "MT",id: 139},
    {value: "Marshall Islands",label: "MH",id: 140},
    {value: "Martinique",label: "MQ",id: 141},
    {value: "Mauritania",label: "MR",id: 142},
    {value: "Mauritius",label: "MU",id: 143},
    {value: "Mayotte",label: "YT",id: 144},
    {value: "Mexico",label: "MX",id: 145},
    {value: "Micronesia, Federated States of",label: "FM",id: 146},
    {value: "Moldova, Republic of",label: "MD",id: 147},
    {value: "Monaco",label: "MC",id: 148},
    {value: "Mongolia",label: "MN",id: 149},
    {value: "Montenegro",label: "ME",id: 150},
    {value: "Montserrat",label: "MS",id: 151},
    {value: "Morocco",label: "MA",id: 152},
    {value: "Mozambique",label: "MZ",id: 153},
    {value: "Myanmar",label: "MM",id: 154},
    {value: "Namibia",label: "NA",id: 155},
    {value: "Nauru",label: "NR",id: 156},
    {value: "Nepal",label: "NP",id: 157},
    {value: "Netherlands",label: "NL",id: 158},
    {value: "Netherlands Antilles",label: "AN",id: 159},
    {value: "New Caledonia",label: "NC",id: 160},
    {value: "New Zealand",label: "NZ",id: 161},
    {value: "Nicaragua",label: "NI",id: 162},
    {value: "Niger",label: "NE",id: 163},
    {value: "Nigeria",label: "NG",id: 164},
    {value: "Niue",label: "NU",id: 165},
    {value: "Norfolk Island",label: "NF",id: 166},
    {value: "Northern Mariana Islands",label: "MP",id: 167},
    {value: "Norway",label: "NO",id: 168},
    {value: "Oman",label: "OM",id: 169},
    {value: "Pakistan",label: "PK",id: 170},
    {value: "Palau",label: "PW",id: 171},
    {value: "Palestinian Territory, Occupied",label: "PS",id: 172},
    {value: "Panama",label: "PA",id: 173},
    {value: "Papua New Guinea",label: "PG",id: 174},
    {value: "Paraguay",label: "PY",id: 175},
    {value: "Peru",label: "PE",id: 176},
    {value: "Philippines",label: "PH",id: 177},
    {value: "Pitcairn",label: "PN",id: 178},
    {value: "Poland",label: "PL",id: 179},
    {value: "Portugal",label: "PT",id: 180},
    {value: "Puerto Rico",label: "PR",id: 181},
    {value: "Qatar",label: "QA",id: 182},
    {value: "Reunion",label: "RE",id: 183},
    {value: "Romania",label: "RO",id: 184},
    {value: "Russian Federation",label: "RU",id: 185},
    {value: "Rwanda",label: "RW",id: 186},
    {value: "Saint Barthelemy",label: "BL",id: 187},
    {value: "Saint Helena",label: "SH",id: 188},
    {value: "Saint Kitts and Nevis",label: "KN",id: 189},
    {value: "Saint Lucia",label: "LC",id: 190},
    {value: "Saint Martin",label: "MF",id: 191},
    {value: "Saint Pierre and Miquelon",label: "PM",id: 192},
    {value: "Saint Vincent and the Grenadines",label: "VC",id: 193},
    {value: "Samoa",label: "WS",id: 194},
    {value: "San Marino",label: "SM",id: 195},
    {value: "Sao Tome and Principe",label: "ST",id: 196},
    {value: "Saudi Arabia",label: "SA",id: 197},
    {value: "Senegal",label: "SN",id: 198},
    {value: "Serbia",label: "RS",id: 199},
    {value: "Serbia and Montenegro",label: "CS",id: 200},
    {value: "Seychelles",label: "SC",id: 201},
    {value: "Sierra Leone",label: "SL",id: 202},
    {value: "Singapore",label: "SG",id: 203},
    {value: "St Martin",label: "SX",id: 204},
    {value: "Slovakia",label: "SK",id: 205},
    {value: "Slovenia",label: "SI",id: 206},
    {value: "Solomon Islands",label: "SB",id: 207},
    {value: "Somalia",label: "SO",id: 208},
    {value: "South Africa",label: "ZA",id: 209},
    {value: "South Georgia and the South Sandwich Islands",label: "GS",id: 210},
    {value: "South Sudan",label: "SS",id: 211},
    {value: "Spain",label: "ES",id: 212},
    {value: "Sri Lanka",label: "LK",id: 213},
    {value: "Sudan",label: "SD",id: 214},
    {value: "Surivalue",label: "SR",id: 215},
    {value: "Svalbard and Jan Mayen",label: "SJ",id: 216},
    {value: "Swaziland",label: "SZ",id: 217},
    {value: "Sweden",label: "SE",id: 218},
    {value: "Switzerland",label: "CH",id: 219},
    {value: "Syrian Arab Republic",label: "SY",id: 220},
    {value: "Taiwan, Province of China",label: "TW",id: 221},
    {value: "Tajikistan",label: "TJ",id: 222},
    {value: "Tanzania, United Republic of",label: "TZ",id: 223},
    {value: "Thailand",label: "TH",id: 224},
    {value: "Timor-Leste",label: "TL",id: 225},
    {value: "Togo",label: "TG",id: 226},
    {value: "Tokelau",label: "TK",id: 227},
    {value: "Tonga",label: "TO",id: 228},
    {value: "Trinidad and Tobago",label: "TT",id: 229},
    {value: "Tunisia",label: "TN",id: 230},
    {value: "Turkey",label: "TR",id: 231},
    {value: "Turkmenistan",label: "TM",id: 232},
    {value: "Turks and Caicos Islands",label: "TC",id: 233},
    {value: "Tuvalu",label: "TV",id: 234},
    {value: "Uganda",label: "UG",id: 235},
    {value: "Ukraine",label: "UA",id: 236},
    {value: "United Arab Emirates",label: "AE",id: 237},
    {value: "United Kingdom",label: "GB",id: 238},
    {value: "United States",label: "US",id: 239},
    {value: "United States Minor Outlying Islands",label: "UM",id: 240},
    {value: "Uruguay",label: "UY",id: 241},
    {value: "Uzbekistan",label: "UZ",id: 242},
    {value: "Vanuatu",label: "VU",id: 243},
    {value: "Venezuela",label: "VE",id: 244},
    {value: "Viet Nam",label: "VN",id: 245},
    {value: "Virgin Islands, British",label: "VG",id: 246},
    {value: "Virgin Islands, U.s.",label: "VI",id: 247},
    {value: "Wallis and Futuna",label: "WF",id: 248},
    {value: "Western Sahara",label: "EH",id: 249},
    {value: "Yemen",label: "YE",id: 250},
    {value: "Zambia",label: "ZM",id: 251},
    {value: "Zimbabwe",label: "ZW",id: 252}
];

  return (
    <div className="content">
      <div className="heading">
        <h2 className="text-white">Online Mailbox</h2>
        <p className="text-white">
          Our company is an Indian company that provides various online
          services, including email. Our company Mail is popular for business
          users and offers a suite of productivity tools.
        </p>
      </div>
      <div className="form-sl">
        <form action="/job-list-sidebar">
          <div className="row-group-search home1">
            <div className="form-group-1">
              <Select options={countries} />
            </div>
            <div className="form-group-4">
              <button type="submit" className="btn btn-find">
                <span className="icon-map-pin"></span>
                Find
              </button>
            </div>
          </div>
        </form>
      </div>
      {/* <ul className="list-category text-white">
        <li>
          <Link to="/aboutus">Designer</Link>
        </li>
        <li className="current">
          <Link to="/aboutus">Developer</Link>
        </li>
        <li>
          <Link to="/aboutus">Tester</Link>
        </li>
        <li>
          <Link to="/aboutus">Writing</Link>
        </li>
        <li>
          <Link to="/aboutus">Project Manager</Link>
        </li>
      </ul> */}
    </div>
  );
}

export default FormContent;
